version: '3.8'

services:
  web:
    container_name: weblog_web
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python srcs/manage.py migrate &&
             python srcs/manage.py collectstatic --noinput &&
             python srcs/manage.py runserver 0.0.0.0:80"
    volumes:
      - ./srcs:/app/srcs
      - static_volume:/app/static
      - media_volume:/app/media
      - sqlite_data:/app/data
    ports:
      - "80:80"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.dev
      - DOCKER_ENV=true
    networks:
      - wagtail_network

volumes:
  static_volume:
  media_volume:
  sqlite_data:

networks:
  wagtail_network:
    driver: bridge 