version: '3.8'

services:
  web:
    container_name: weblog_web
    build:
      context: .
      dockerfile: Dockerfile
    command: python srcs/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.dev
    depends_on:
      - db
    networks:
      - wagtail_network

  db:
    container_name: weblog_db
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=weblog
      - POSTGRES_USER=weblog
      - POSTGRES_PASSWORD=weblog
    networks:
      - wagtail_network

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  wagtail_network:
    driver: bridge 