# Generated by Django 5.2.3 on 2025-06-18 08:34

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body_homepage_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('markdown', 0), ('heading', 1), ('paragraph', 2), ('image', 3)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {'help_text': 'Markdown text'}), 1: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 2: ('wagtail.blocks.RichTextBlock', (), {}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {})}),
        ),
    ]
