# Generated by Django 5.2.3 on 2025-06-18 07:52

import django.utils.timezone
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0002_blogpage_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', 0), ('image', 1)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {})}, null=True),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='body_markdown',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Post date'),
        ),
    ]
