# Generated by Django 5.2.3 on 2025-06-18 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0003_category_cover_image_homepage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
