# Generated by Django 5.2.3 on 2025-06-18 08:26

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0004_blogpage_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='body_markdown',
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('markdown', 0), ('paragraph', 1), ('image', 2)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {'help_text': 'Markdown text'}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {})}, null=True),
        ),
    ]
