# Generated by Django 5.2.3 on 2025-06-18 14:31

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0004_delete_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
